# Generated by Django 3.1 on 2021-05-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
