# Generated by Django 3.2.4 on 2021-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210606_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
