# Generated by Django 3.2.4 on 2021-06-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20210526_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileclient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profileprovider',
            name='id',
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profileprovider',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
