# Generated by Django 3.2.4 on 2021-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20210605_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileclient',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profileprovider',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
