# Generated by Django 3.2.4 on 2021-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20210606_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileclient',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profileprovider',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
