# Generated by Django 3.2.4 on 2021-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20210606_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileclient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profileprovider',
            name='id',
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profileprovider',
            name='slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
