# Generated by Django 3.2.3 on 2021-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='main_image',
            field=models.ImageField(default='default-avatar.jpg', upload_to='main_catering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodging',
            name='main_image',
            field=models.ImageField(default='default-avatar.jpg', upload_to='main_lodging'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='main_image',
            field=models.ImageField(default='default-avatar.jpg', upload_to='main_place'),
            preserve_default=False,
        ),
    ]
